language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
  max_iterations: 150
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: RegexEntityExtractor
  "case_sensitive": False
  "use_lookup_tables": True
  "use_regexes": True  
- name: DucklingEntityExtractor
  url: http://duckling:7000
  dimensions:
  - sys_time
  - sys_day
  - sys_month
  - sys_year
  - phone-number
  - number
  - amount-of-money
  - distance
  - duration
  - volume
  - ordinal
  - temperature
  - email
  - url
  - time
- name: DIETClassifier
  epochs: 30
- name: FallbackClassifier
  threshold: 0.5
  ambiguity_threshold: 0.1

policies:
  # - name: AugmentedMemoizationPolicy
  # - name: TEDPolicy
  #   epochs: 50
  - name: RulePolicy
    core_fallback_threshold: 0.4
    enable_fallback_prediction: True
    core_fallback_action_name: "action_default_fallback"
